### ISSUE TITLE
Django 1.7 on Python 3

### ISSUE THREAD

**Issue by dstegelman** [dstegelman/django-mail-queue#47]
```
Traceback (most recent call last):
  File "/home/vagrant/django-mail-queue/mailqueue/tests/__init__.py", line 103, in test_add_multiple_attachments
    test_message.save()
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 591, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 628, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.4/dist-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/vagrant/django-mail-queue/mailqueue/models.py", line 147, in send_post_save
    instance.send_mail()
  File "/home/vagrant/django-mail-queue/mailqueue/models.py", line 94, in send_mail
    self._send()
  File "/home/vagrant/django-mail-queue/mailqueue/models.py", line 113, in _send
    msg.send()
  File "/usr/local/lib/python3.4/dist-packages/django/core/mail/message.py", line 286, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.4/dist-packages/django/core/mail/backends/locmem.py", line 26, in send_messages
    message.message()
  File "/usr/local/lib/python3.4/dist-packages/django/core/mail/message.py", line 253, in message
    msg = self._create_message(msg)
  File "/usr/local/lib/python3.4/dist-packages/django/core/mail/message.py", line 409, in _create_message
    return self._create_attachments(self._create_alternatives(msg))
  File "/usr/local/lib/python3.4/dist-packages/django/core/mail/message.py", line 325, in _create_attachments
    msg.attach(self._create_attachment(*attachment))
  File "/usr/local/lib/python3.4/dist-packages/django/core/mail/message.py", line 367, in _create_attachment
    attachment = self._create_mime_attachment(content, mimetype)
  File "/usr/local/lib/python3.4/dist-packages/django/core/mail/message.py", line 338, in _create_mime_attachment
    attachment = SafeMIMEText(content, subtype, encoding)
  File "/usr/local/lib/python3.4/dist-packages/django/core/mail/message.py", line 175, in __init__
    MIMEText.__init__(self, text, subtype, None)
  File "/usr/lib/python3.4/email/mime/text.py", line 33, in __init__
    _text.encode('us-ascii')
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by dstegelman** [comment]
Seems to be an issue in Django 1.7 core.  Resolved in later releases
